/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class derek_licrecndk4_MainActivity */

#ifndef _Included_derek_licrecndk4_MainActivity
#define _Included_derek_licrecndk4_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     derek_licrecndk4_MainActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_derek_licrecndk4_MainActivity_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
